# Generated by Django 3.1 on 2020-08-11 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='instructions',
            new_name='instruction',
        ),
    ]
